import { createFileRoute } from "@tanstack/react-router";
import { useEffect, useState } from "react";
import { adminApproveDreamVoraPayment, adminListDreamVoraPayments, adminLoginDreamVora, adminRejectDreamVoraPayment } from "@/lib/dreamvora.server";

export const Route = createFileRoute("/admin")({ head: () => ({ meta: [{ title: "Admin — DreamVora" }, { name: "robots", content: "noindex, nofollow" }] }), component: AdminPage });

type Payment = { id:string; phone_used:string; amount:number; currency:string; provider:string; provider_order_id:string|null; reference:string|null; channel:string|null; status:string; provider_status:string|null; submitted_at:string; confirmed_at:string|null; approved_at:string|null; rejected_at:string|null; transid:string|null; name:string; username:string; account_phone:string; email:string };

function AdminPage(){
 const [password,setPassword]=useState(""); const [token,setToken]=useState<string|null>(()=>typeof window!=="undefined"?sessionStorage.getItem("dreamvora_admin"):null); const [payments,setPayments]=useState<Payment[]>([]); const [error,setError]=useState<string|null>(null); const [busy,setBusy]=useState<string|null>(null);
 async function login(e:React.FormEvent){e.preventDefault();setError(null);try{const r=await adminLoginDreamVora({data:{password}});sessionStorage.setItem("dreamvora_admin",r.token);setToken(r.token);setPassword("");}catch(err){setError(err instanceof Error?err.message:"Admin login imeshindikana.")}}
 async function load(){if(!token)return;try{const r=await adminListDreamVoraPayments({data:{token}});setPayments(r.payments as Payment[]);setError(null)}catch(err){setError(err instanceof Error?err.message:"Imeshindikana kupakia malipo.")}}
 useEffect(()=>{void load();if(!token)return;const t=window.setInterval(()=>void load(),5000);return()=>window.clearInterval(t)},[token]);
 async function approve(id:string){if(!token)return;setBusy(id);try{await adminApproveDreamVoraPayment({data:{token,paymentId:id}});await load()}catch(err){setError(err instanceof Error?err.message:"Imeshindikana ku-approve.")}finally{setBusy(null)}}
 async function reject(id:string){if(!token)return;setBusy(id);try{await adminRejectDreamVoraPayment({data:{token,paymentId:id}});await load()}catch(err){setError(err instanceof Error?err.message:"Imeshindikana ku-reject.")}finally{setBusy(null)}}
 if(!token)return <main className="min-h-screen bg-k-slate-50 flex items-center justify-center p-4"><form onSubmit={login} className="w-full max-w-md rounded-3xl bg-white p-7 shadow-xl"><h1 className="text-2xl font-extrabold text-k-slate-900">DreamVora Admin</h1><p className="mt-2 text-sm text-k-slate-500">Ingia kuona na kuthibitisha maombi ya USSD Push.</p>{error&&<div className="mt-4 rounded-xl bg-red-50 p-3 text-sm font-semibold text-red-700">{error}</div>}<input className="k-field mt-5" type="password" placeholder="Admin password" value={password} onChange={e=>setPassword(e.target.value)} required/><button className="k-btn mt-3" type="submit">Ingia Admin</button></form></main>;
 return <main className="min-h-screen bg-k-slate-50 p-4 md:p-8"><div className="mx-auto max-w-6xl"><div className="flex items-center justify-between gap-3"><div><h1 className="text-2xl font-extrabold text-k-slate-900">Malipo ya DreamVora</h1><p className="text-sm text-k-slate-500">Maombi mapya hu-refresh kila sekunde 5.</p></div><button onClick={()=>{sessionStorage.removeItem("dreamvora_admin");setToken(null)}} className="rounded-xl bg-k-slate-900 px-4 py-2 text-sm font-bold text-white">Toka</button></div>{error&&<div className="mt-4 rounded-xl bg-red-50 p-3 text-sm font-semibold text-red-700">{error}</div>}<div className="mt-6 space-y-3">{payments.length===0?<div className="rounded-2xl bg-white p-8 text-center text-sm text-k-slate-500">Hakuna maombi ya malipo bado.</div>:payments.map(p=><article key={p.id} className="rounded-2xl bg-white p-4 shadow-sm border border-k-slate-200"><div className="flex flex-col gap-4 md:flex-row md:items-center md:justify-between"><div><div className="font-extrabold text-k-slate-900">{p.name} <span className="font-normal text-k-slate-500">(@{p.username})</span></div><div className="mt-1 text-xs text-k-slate-500">Account: {p.account_phone} • {p.email}</div><div className="mt-2 text-sm">Simu iliyolipia: <strong>{p.phone_used}</strong> • Mtandao: <strong>{p.channel||"—"}</strong></div><div className="text-sm">Kiasi: <strong>TZS {p.amount.toLocaleString()}</strong> • Provider: <strong>{p.provider}</strong></div><div className="text-xs text-k-slate-500">Provider status: {p.provider_status||"PENDING"} • Ref: {p.reference||"—"}</div><div className="text-[11px] text-k-slate-400">{new Date(p.submitted_at).toLocaleString("sw-TZ")}</div></div><div className="flex flex-wrap items-center gap-2"><span className={`rounded-full px-3 py-1 text-xs font-extrabold ${p.status==="PENDING_ADMIN"?"bg-amber-100 text-amber-800":p.status==="APPROVED"?"bg-emerald-100 text-emerald-800":p.status==="REJECTED"||p.status==="FAILED"?"bg-red-100 text-red-800":"bg-blue-100 text-blue-800"}`}>{p.status}</span>{p.status==="PENDING_ADMIN"&&<><button disabled={busy===p.id} onClick={()=>void approve(p.id)} className="rounded-xl bg-emerald-600 px-4 py-2 text-xs font-extrabold text-white disabled:opacity-50">{busy===p.id?"...":"APPROVE"}</button><button disabled={busy===p.id} onClick={()=>void reject(p.id)} className="rounded-xl bg-red-600 px-4 py-2 text-xs font-extrabold text-white disabled:opacity-50">REJECT</button></>}</div></div></article>)}</div></div></main>;
}
